server:
  port: 8080


spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: productos
          uri: http://localhost:8090
          predicates:
            - Path=/api/producto/**

        - id: pedidos
          uri: http://localhost:9090
          predicates:
            - Path=/api/pedido/**

